[build]
  command = "yarn build"
  publish = ".next"

[functions]
  directory = ".next/server/functions"

[[headers]]
  for = "/*"
  [headers.values]
  cache-control = 'max-age=0,no-cache,no-store,must-revalidate'